<?xml version="1.0" encoding="utf-8"?><Database Name="SmartBus" Class="DataSmartBusDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=SmartBus;Integrated Security=True" SettingsObjectName="ProjectSmartBus.Properties.Settings" SettingsPropertyName="SmartBusConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ThongTinKhachHang" Member="ThongTinKhachHangs">
    <Type Name="ThongTinKhachHang">
      <Column Name="ID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="SoTienHienTai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CheckHanhDong" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>